version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:1.20.2-alpine
        container_name: ${NGINX_CONTAINER:-nginx}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/cert:/etc/cert
            - ./nginx/log:/var/log/nginx
        environment:
            TZ: ${TZ:-Asia/Shanghai}
        depends_on:
            - php7
            - mariadb
        privileged: true
        networks:
            - lemp
    mariadb:
        image: mariadb:latest
        container_name: ${MARIADB_CONTAINER:-mariadb}
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            LANG: C.UTF-8
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Shanghai}
        networks:
            - lemp
    php7:
        build:
            context: ./php/.
            dockerfile: Dockerfile_php_7.4.12-fpm
        image: df_php_7.4.12-fpm
        container_name: ${PHP7_CONTAINER:-php7}
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - lemp
    redis:
        image: redis:6.2.6-alpine
        container_name: ${REDIS_CONTAINER:-redis}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
        ports:
            - "6379:6379"
        networks:
            - lemp
    pma:
        image: phpmyadmin:latest
        container_name: ${PMA_CONTAINER:-pma}
        ports:
            - "8080:80"
        environment:
            PMA_HOST: ${PMA_HOST:-mariadb}
        networks:
          - lemp
    mailcatcher:
        image: schickling/mailcatcher
        container_name: ${MAILCATCHER_CONTAINER:-mailcatcher}
        ports:
            - "1081:1080"
        networks:
            - lemp
