version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:1.23.0-alpine
        container_name: ${NGINX_CONTAINER:-nginx}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/cert:/etc/cert
            - ./nginx/log:/var/log/nginx
        environment:
            TZ: ${TZ:-Asia/Shanghai}
        depends_on:
            - php7
            - mysql
        privileged: true
        networks:
            - lemp
    mysql:
        image: mysql:8.0.29
        container_name: ${MYSQL_CONTAINER:-mysql}
        ports:
            - "33306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            LANG: C.UTF-8
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Shanghai}
        networks:
            - lemp
    php7:
        build:
            context: ./php/.
            dockerfile: Dockerfile_php_7.4.29-fpm
        image: df_php_7.4.29-fpm
        container_name: ${PHP7_CONTAINER:-php7}
        volumes:
            - ./src:/var/www/html
        ports:
            - "127.0.0.1:9000:9000"
        networks:
            - lemp
    redis:
        image: redis:7.0.2-alpine
        container_name: ${REDIS_CONTAINER:-redis}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
        ports:
            - "127.0.0.1:6379:6379"
        networks:
            - lemp
    pma:
        image: phpmyadmin:latest
        container_name: ${PMA_CONTAINER:-pma}
        ports:
            - "30080:80"
        environment:
            PMA_HOST: ${PMA_HOST:-mysql}
        networks:
          - lemp
    mailcatcher:
        image: schickling/mailcatcher
        container_name: ${MAILCATCHER_CONTAINER:-mailcatcher}
        ports:
            - "1081:1080"
        networks:
            - lemp
    meilisearch:
        image: getmeili/meilisearch:v0.25.2
        container_name: ${MEILISEARCH_CONTAINER:-meilisearch}
        volumes:
            - ./meilisearch/data.ms:/data.ms
        ports:
            - "37700:7700"
        environment:
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
        networks:
            - lemp 
